version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - $HOME/.config/gcloud/application_default_credentials.json:/credentials/application_default_credentials.json
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=imgcp-20220315135638
